version: "3"
services:
  guacamole:
    image: jwetzell/guacamole:arm32v7
    container_name: guacamole
    volumes:
      - ./postgres:/config
    ports:
      - 8080:8080
volumes:
  postgres:
    driver: local
